version: "3"
services:
   configuration:
      image: josemartinezg/cojo-config-service
      networs:
         - cojo-events
      volumes:
         - /var/centralConfiguration
      ports:
         - 8888:8888
      restart: on-failure
      logging:
         driver: none

   discovery:
      image: josemartinezg/cojo-eureka-service
      networs:
         - cojo-events
      depends_on: :
         - configuration
      ports:
         - 8761:8761
      environment:
         - spring.cloud.config.uri=http://configuration:8888
      restart: on-failure
      logging:
         driver: none
      
   perimetral:
      image: josemartinezg/cojo-perimetral-service
      networs:
         - cojo-events
      depends_on: :
         - configuration
         - discovery
      ports:
      environment:
         - spring.cloud.config.uri=http://configuration:8888
         - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      restart: on-failure
      logging:
         driver: none

   usuario-service1:
      image: josemartinezg/cojo-usuario-service
      networks:
         - cojo-events
      depends_on:
         - dbusuario
         - configuration
         - discovery
         - perimetral
      expose:
         - 200-65000
      environment:
         - spring.cloud.config.uri=http://configuration:8888
         - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
         - spring.datasource.url=jdbc:mysql://dbusuario:3306/cojo_events_usuarios
      restart: on-failure:2

   usuario-service2:
      image: josemartinezg/cojo-usuario-service
      networks:
         - cojo-events
      depends_on:
         - dbusuario
         - configuration
         - discovery
         - perimetral
      expose:
         - 200-65000
      environment:
         - spring.cloud.config.uri=http://configuration:8888
         - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
         - spring.datasource.url=jdbc:mysql://dbusuario:3306/cojo_events_usuarios
      restart: on-failure:2

   usuario-service3:
      image: josemartinezg/cojo-usuario-service
      networks:
         - cojo-events
      depends_on:
         - dbusuario
         - configuration
         - discovery
         - perimetral
      expose:
         - 200-65000
      environment:
         - spring.cloud.config.uri=http://configuration:8888
         - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
         - spring.datasource.url=jdbc:mysql://dbusuario:3306/cojo_events_usuarios
      restart: on-failure:2

   compra-service1:
      image: josemartinezg/cojo-compra-service
      networks:
         - cojo-events
      depends_on:
         - dbcompras
         - configuration
         - discovery
         - perimetral
      expose:
         - 200-65000
      environment:
         - spring.cloud.config.uri=http://configuration:8888
         - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
         - spring.datasource.url=jdbc:mysql://dbusuario:3306/cojo_events_compras
      restart: on-failure:2

   compra-service2:
      image: josemartinezg/cojo-compra-service
      networks:
         - cojo-events
      depends_on:
         - dbcompras
         - configuration
         - discovery
         - perimetral
      expose:
         - 200-65000
      environment:
         - spring.cloud.config.uri=http://configuration:8888
         - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
         - spring.datasource.url=jdbc:mysql://dbusuario:3306/cojo_events_compras
      restart: on-failure:2

      compra-service3:
      image: josemartinezg/cojo-compra-service
      networks:
         - cojo-events
      depends_on:
         - dbcompras
         - configuration
         - discovery
         - perimetral
      expose:
         - 200-65000
      environment:
         - spring.cloud.config.uri=http://configuration:8888
         - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
         - spring.datasource.url=jdbc:mysql://dbusuario:3306/cojo_events_compras
      restart: on-failure:2
   
   dbusuario:
      image: library/mysql:latest
      networks:
         - cojo-events
      ports:
         - "33006:3306"
      environment:
         - MYSQL_USER=root
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=cojo_events_usuarios
      volumes:   
         - ~/dato_mysql_final:/var/lib/mysql

   dbcompras:
      image: library/mysql:latest
      networks:
         - cojo-events
      ports:
         - "33006:3306"
      environment:
         - MYSQL_USER=root
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=cojo_events_compras
      volumes:   
         - ~/dato_mysql_final:/var/lib/mysql

   networks:
      cojo-events:
      
      
   